// ============================================================
// 🤖 AI Advisory Model (Collection: advisories) — STEP 4.2
// ============================================================
//
// PURPOSE:
//   Stores every AI advisory interaction — questions asked by
//   users and responses generated by Gemini AI.
//
//   This supports:
//   • Query history (so farmers can review past advice)
//   • Bookmarking (save useful advisories for later)
//   • Rating (feedback loop for advisory quality)
//   • Token tracking (monitor API usage & costs)
//   • Category-based organization (disease, soil, planning)
//   • Optional disease report linking (when advisory is
//     triggered by a disease detection)
//
// RELATIONSHIPS:
//   User (1) ──> (N) Advisory
//   Farm (1) ──> (N) Advisory  (optional)
//   Disease (1) ──> (N) Advisory  (optional — when linked to scan)
//
// ============================================================

const mongoose = require("mongoose");

// -----------------------------------------------------------
// Token Usage Sub-Schema
// -----------------------------------------------------------
// Tracks how many API tokens each advisory consumes.
// This data helps monitor costs and optimize prompts.
// -----------------------------------------------------------
const tokenUsageSchema = new mongoose.Schema(
    {
        prompt: {
            type: Number,
            default: 0,
        },
        response: {
            type: Number,
            default: 0,
        },
        total: {
            type: Number,
            default: 0,
        },
    },
    { _id: false }
);

// -----------------------------------------------------------
// Main Advisory Schema
// -----------------------------------------------------------
const advisorySchema = new mongoose.Schema(
    {
        // ---------------------------------------------------
        // References
        // ---------------------------------------------------
        user: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            required: [true, "Advisory must belong to a user"],
            index: true,
        },

        farm: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Farm",
            // Optional — user can ask without linking to farm
        },

        // Link to disease report (when advisory is triggered
        // by a disease detection scan)
        diseaseReport: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Disease",
            // Optional — only set for disease-related advisories
        },

        // ---------------------------------------------------
        // Query & Context
        // ---------------------------------------------------

        // The user's original question
        query: {
            type: String,
            required: [true, "Please provide a query"],
            maxlength: [2000, "Query cannot exceed 2000 characters"],
            trim: true,
        },

        // Context data sent with the query — makes Gemini responses
        // more relevant by providing farm-specific information
        context: {
            cropType: String,
            soilType: String,
            season: String,
            location: String,
            area: String,
            farmingMethod: String,
            diseaseDetected: String,
            diseaseConfidence: Number,
            diseaseSeverity: String,
        },

        // ---------------------------------------------------
        // Gemini AI Response
        // ---------------------------------------------------

        // The full AI-generated response text
        response: {
            type: String,
            required: [true, "Advisory response is required"],
        },

        // Confidence-based preamble (high/moderate/low confidence text)
        preamble: {
            type: String,
            default: "",
        },

        // Action urgency derived from ML + Gemini combination logic
        actionUrgency: {
            type: String,
            enum: ["none", "low", "normal", "moderate", "high", "very_low"],
            default: "normal",
        },

        // ---------------------------------------------------
        // Category & Type
        // ---------------------------------------------------
        category: {
            type: String,
            enum: [
                "disease-treatment",
                "pest-control",
                "soil-management",
                "irrigation",
                "fertilization",
                "crop-planning",
                "cost-estimation",
                "weather",
                "general",
            ],
            default: "general",
            index: true,
        },

        // Prompt template that was used
        promptTemplate: {
            type: String,
            enum: [
                "disease",
                "general",
                "crop-planning",
                "soil",
                "cost-estimation",
            ],
            default: "general",
        },

        // ---------------------------------------------------
        // API Usage Tracking
        // ---------------------------------------------------
        tokensUsed: tokenUsageSchema,

        // ---------------------------------------------------
        // User Interaction
        // ---------------------------------------------------

        // Quality rating (1-5 stars)
        rating: {
            type: Number,
            min: 1,
            max: 5,
        },

        // User bookmarked this advisory for future reference
        isBookmarked: {
            type: Boolean,
            default: false,
        },

        // User marked this advisory as helpful
        isHelpful: {
            type: Boolean,
            default: null, // null = not rated, true = helpful, false = not helpful
        },

        // User notes (farmer can add their own notes on the advisory)
        userNotes: {
            type: String,
            maxlength: 1000,
            default: "",
        },

        // ---------------------------------------------------
        // Status
        // ---------------------------------------------------
        // Whether a fallback response was used (Gemini was unavailable)
        isFallback: {
            type: Boolean,
            default: false,
        },
    },
    {
        timestamps: true,
    }
);

// ============================================================
// INDEXES
// ============================================================
advisorySchema.index({ user: 1, createdAt: -1 });
advisorySchema.index({ user: 1, category: 1 });
advisorySchema.index({ user: 1, isBookmarked: 1 });
advisorySchema.index({ diseaseReport: 1 });
advisorySchema.index({ farm: 1, createdAt: -1 });

module.exports = mongoose.model("Advisory", advisorySchema);
